"""remove fk from students

Revision ID: 14b097a527b2
Revises: 0f4d923e7977
Create Date: 2018-03-14 21:16:49.866338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b097a527b2'
down_revision = '0f4d923e7977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_course_id_fkey', 'students', type_='foreignkey')
    op.drop_constraint('students_student_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'course_id')
    op.drop_column('students', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('students_student_id_fkey', 'students', 'students', ['student_id'], ['id'])
    op.create_foreign_key('students_course_id_fkey', 'students', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
